// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/service-cards/Glassmorphisme.tsx": () => import("../components/mockups/service-cards/Glassmorphisme.tsx"),
  "./components/mockups/service-cards/GradientBold.tsx": () => import("../components/mockups/service-cards/GradientBold.tsx"),
  "./components/mockups/service-cards/MagazineEditorial.tsx": () => import("../components/mockups/service-cards/MagazineEditorial.tsx"),
  "./components/mockups/service-cards/MinimalEpure.tsx": () => import("../components/mockups/service-cards/MinimalEpure.tsx")
};
